#rss
rss:
  # 是否推送
  push: true
  # 控制检查更新频率
  cron: "*/10 * * * *"
  # 发送主动推送消息的bot，填入字符串qq号，例如["12345667"]
  # sender: []
  # rsshub地址，可以填自建地址或官方反代
  rsshub_url:
    - https://rsshub.app
    - https://rsshub.zytomorrow.top
  # 默认图片背景
  background: https://api.armoe.cn/acg/random
  # 订阅rss列表
  subscribe_list:
    - url: ${rsshub_url}/yxdzqb/low
      name: Steam史低
      group: []

#epic
epicGames:
  isPush: true
  schedule:
    month: "*" # 每个月都执行
    dayOfWeek: "5,0" # 在周五和周日执行（星期天是 0）
    hour: "12" # 在中午12:00:00执行
    minute: "0"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
#read60s
read60s:
  isPush: true
  schedule:
    hour: "8" # 在中午8:00:00执行
    minute: "20"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
aiNews:
  isPush: true
  schedule:
    hour: "8" # 在早上8:00:00执行
    minute: "30"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
#翻译
translate:
  baidu:
    id: null
    key: null
  youdao:
    id: null
    key: null

# 油价查询
oilPrice:
  isPush: true
  schedule:
    year: "*"
    month: "*"
    week: "5" # 在周五和周日执行（星期天是 0）
    hour: "8" # 在早上8:00:00执行
    minute: "30"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
  #需要推送的省份
  provinces: ["江苏"]

# Warframe
warframe:
  server: "ZHCN" # 选择服务器，ZHCN为国服，ZH为国际服

screenshot:
  fullScreen: true
  quality: 80
  minWidth: 800
  maxWidth: 1920
  padding: 80
  timeout:
    page: 60000
    resource: 30000
    render: 10000
  proxyApi:
    url: "https://proxyapi.198143.xyz/"
    enabled: true

# Html渲染精度，可选值50~200，建议100。设置高精度会提高图片的精细度，过高可能会影响渲染与发送速度
renderScale: 100

# BT搜索配置
bt:
  proxy:
    enable: false
    url: "http://127.0.0.1:7890" # 代理地址，例如 http://127.0.0.1:7890
  proxyApi:
    enable: true
    url: "https://proxyapi.198143.xyz/{{url}}"
