#epic
epicGames:
  isPush: true
  schedule:
    month: "*" # 每个月都执行
    dayOfWeek: "5,0" # 在周五和周日执行（星期天是 0）
    hour: "12" # 在中午12:00:00执行
    minute: "0"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
#read60s
read60s:
  isPush: true
  schedule:
    hour: "8" # 在中午8:00:00执行
    minute: "20"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
aiNews:
  isPush: true
  schedule:
    hour: "8" # 在早上8:00:00执行
    minute: "30"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
#翻译
baidu_translate:
  id: null
  key: null
youdao_translate:
  id: null
  key: null

# 油价查询
oilPrice:
  isPush: true
  schedule:
    year: "*"
    month: "*"
    week: "5" # 在周五和周日执行（星期天是 0）
    hour: "8" # 在早上8:00:00执行
    minute: "30"
    second: "0"
  #配置定时发送群组和需要私聊发送的人
  group_ids: []
  private_ids: []
  #需要推送的省份
  provinces: ["江苏"]

# Warframe
warframe:
  server: "CN" # 选择服务器，ZHCN为国服，ZH为国际服



# Html渲染精度，可选值50~200，建议100。设置高精度会提高图片的精细度，过高可能会影响渲染与发送速度
renderScale: 100
