rss:
  # 控制检查更新频率
  cron: "*/30 * * * *"
  # 发送主动推送消息的bot，填入字符串qq号，例如["12345667"]
  # sender: []
  # 默认发送到哪些群，如["12345678", "23456789"]
  default_group: []
  # rsshub地址，可以填自建地址或官方反代
  rsshub_url:
    - https://rsshub.zytomorrow.top
    - https://rss.datuan.dev
    - https://rsshub.asailor.org
    - https://rsshub.cups.moe
    - https://rsshub.rssforever.com
    - https://hub.slarker.me
    - https://rsshub.pseudoyu.com
    - https://rsshub.ktachibana.party
    - https://rsshub.umzzz.com
    - https://rsshub.isrss.com
    - https://rsshub.app
  # 默认图片背景
  background: https://api.armoe.cn/acg/random
  # 订阅rss列表
  subscribe_list:
    - url: ${rsshub_url}/4khd/category/cosplay
      name: 4khd
      group: ["959969379"]
    - url: ${rsshub_url}/yxdzqb/low
      name: Steam史低
      group: ["959969379"]
    - url: ${rsshub_url}/misskon/posts/search=video
      name: Misskon
      group: ["959969379"]
    - url: ${rsshub_url}/misskon/posts
      name: Hentai
      group: ["959969379"]
    - url: ${rsshub_url}/everia/category/chinese
      name: EveriaXiuren
      group: ["959969379"]
    - url: ${rsshub_url}/everia/category/cosplay
      name: EveriaCosplay
      group: ["959969379"]
    - url: ${rsshub_url}/cosplaytele
      name: CosplayTele
      group: ["959969379"]
    - url: ${rsshub_url}/jpxgmn/weekly
      name: Girls
      group: ["959969379"]
    - url: ${rsshub_url}/4kup/category/coser
      name: 4kupCoser
      group: ["959969379"]
    - url: ${rsshub_url}/4kup/category/korean
      name: 4kupKorean
      group: ["959969379"]
epicGames:
  isPush: true
  schedule:
    month: "*"
    dayOfWeek: 5,0
    hour: "12"
    minute: "0"
    second: "0"
  group_ids:
    - "1035210666"
    - "959969379"
  private_ids: []
read60s:
  isPush: true
  schedule:
    hour: "8"
    minute: "20"
    second: "0"
  group_ids:
    - "1035210666"
    - "959969379"
  private_ids: []
aiNews:
  isPush: true
  schedule:
    hour: "9"
    minute: "11"
    second: "0"
  group_ids:
    - "959969379"
  private_ids: []
baidu_translate:
  id: null
  key: null
youdao_translate:
  id: null
  key: null
oilPrice:
  isPush: true
  schedule:
    year: "*"
    month: "*"
    week: "5"
    hour: "8"
    minute: "30"
    second: "0"
  group_ids:
    - "959969379"
  private_ids: []
  provinces:
    - 江苏
    - 福建
warframe:
  server: ZHCN
screenshot:
  fullScreen: true
  quality: 80
  minWidth: 800
  maxWidth: 1920
  padding: 80
  timeout:
    page: 60000
    resource: 30000
    render: 10000
  proxyApi:
    url: https://proxyapi.198143.xyz/
    enabled: true
renderScale: 100
bt:
  proxy:
    enable: false
    url: http://127.0.0.1:7890
  proxyApi:
    enable: true
    url: https://proxyapi.198143.xyz/{{url}}
